name: CI Docker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Construir imagen Docker
        run: docker build -t computacion-ejercicio6 .

      - name: Ejecutar tests dentro del contenedor
        run: docker run --rm computacion-ejercicio6